
alertmanager:
  enabled: true

  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'sathishcool444@gmail.com'
      smtp_auth_username: 'sathishcool444@gmail.com'
      smtp_auth_password_file: '/etc/alertmanager/secrets/alertmanager-gmail/smtp-auth-password'
      smtp_require_tls: true

    route:
      group_by:
        - alertname
        - namespace
        - severity
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'devsecops-gmail'
      routes:
        - receiver: 'null'
          matchers:
            - 'alertname = "Watchdog"'

    receivers:
      - name: 'devsecops-gmail'
        email_configs:
          - to: 'sathishcool444@gmail.com'
            send_resolved: true

      - name: 'null'

  alertmanagerSpec:
    replicas: 1
    secrets:
      - alertmanager-gmail

grafana:
  enabled: true
  
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      url: http://loki-gateway.loki.svc.cluster.local
      access: proxy
      isDefault: false

prometheus:
  enabled: true
