cat > monitoring-values.yaml <<'EOF'
alertmanager:
  enabled: true

  alertmanagerSpec:
    replicas: 1
    secrets:
      - alertmanager-gmail

  config:
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'sathishcool444@gmail.com'
      smtp_auth_username: 'sathishcool444@gmail.com'
      smtp_auth_password_file: '/etc/alertmanager/secrets/alertmanager-gmail/smtp-auth-password'
      smtp_require_tls: true

    route:
      group_by:
        - alertname
        - namespace
        - severity
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'devsecops-gmail'
      routes:
        - matchers:
            - 'alertname = "Watchdog"'
          receiver: 'null'

    receivers:
      - name: 'devsecops-gmail'
        email_configs:
          - to: 'sathishcool444@gmail.com'
            send_resolved: true

      - name: 'null'

    inhibit_rules:
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - namespace
          - alertname

      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - namespace
          - alertname

    templates:
      - '/etc/alertmanager/config/*.tmpl'

grafana:
  enabled: true

prometheus:
  enabled: true
EOF