
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devsecops

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: 425034746703.dkr.ecr.ap-south-1.amazonaws.com/devsecops-frontend

          ports:
            - containerPort: 80
            
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devsecops

spec:
  type: ClusterIP
  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 80


