apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devsecops

resources:
  - namespace.yaml

  - user-service.yaml
  - product-service.yaml
  - order-service.yaml
  - frontend.yaml

  - gatewayclass.yaml
  - gateway.yaml

  - frontend-httproute.yaml
  - user-httproute.yaml
  - product-httproute.yaml
  - order-httproute.yaml

  - target-group-config.yaml
  - loadbalancer-config.yaml

  - monitoring/servicemonitor.yaml
  - monitoring/alerts/devsecops-alerts.yaml

  

images:
  - name: 124666675720.dkr.ecr.ap-south-1.amazonaws.com/devsecops-user-service
    newTag: "11"

  - name: 124666675720.dkr.ecr.ap-south-1.amazonaws.com/devsecops-product-service
    newTag: "11"

  - name: 124666675720.dkr.ecr.ap-south-1.amazonaws.com/devsecops-order-service
    newTag: "11"

  - name: 124666675720.dkr.ecr.ap-south-1.amazonaws.com/devsecops-frontend
    newTag: "11"