apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: devsecops-alb-config
  namespace: devsecops
spec:
  scheme: internet-facing
  
  listenerConfigurations:
    - protocolPort: HTTPS:443
      defaultCertificate: arn:aws:acm:ap-south-1:124666675720:certificate/09447a50-5f62-4d14-99e4-05d42f74926d

  