apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: devsecops

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: 425034746703.dkr.ecr.ap-south-1.amazonaws.com/devsecops-product-service

          ports:
            - containerPort: 8082

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DB_HOST

            - name: DB_NAME
              value: productdb

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: JWT_SECRET

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: devsecops

spec:
  selector:
    app: product-service

  ports:
    - name: http
      port: 8082
      targetPort: 8082

  type: ClusterIP
