apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: devsecops

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: 425034746703.dkr.ecr.ap-south-1.amazonaws.com/devsecops-user-service

          ports:
            - containerPort: 8081

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DB_HOST

            - name: DB_NAME
              value: userdb

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: JWT_SECRET

            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: devsecops-secrets
                  key: JWT_EXPIRATION

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: devsecops
  labels:
    app: user-service
spec:
  selector:
    app: user-service

  ports:
    - name: http
      port: 8081
      targetPort: 8081

  type: ClusterIP