apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: devsecops-gmail
  namespace: monitoring
  labels:
    release: monitoring

spec:
  route:
    receiver: devsecops-gmail
    groupBy:
      - alertname
      - namespace
      - severity
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h

  receivers:
    - name: devsecops-gmail
      emailConfigs:
        - to: sathishcool444@gmail.com
          from: sathishcool444@gmail.com
          smarthost: smtp.gmail.com:587
          authUsername: sathishcool444@gmail.com
          authPassword:
            name: alertmanager-gmail
            key: smtp-auth-password
          requireTLS: true
          sendResolved: true