apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: user-service-pre-promotion
  namespace: devsecops

spec:
  metrics:

    # 1. Error rate must remain below 5%
    - name: error-rate
      interval: 30s
      count: 3
      failureLimit: 1

      successCondition: result[0] < 0.05

      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

          query: |
            (
              sum(
                rate(
                  http_server_requests_seconds_count{
                    namespace="devsecops",
                    job="{{args.service-name}}",
                    status=~"5.."
                  }[5m]
                )
              )
              /
              sum(
                rate(
                  http_server_requests_seconds_count{
                    namespace="devsecops",
                    job="{{args.service-name}}"
                  }[5m]
                )
              )
            )
            or vector(0)

    # 2. Average latency must remain below 1000ms
    - name: latency
      interval: 30s
      count: 3
      failureLimit: 1

      successCondition: result[0] < 1000

      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

          query: |
            1000 *
            sum(
              rate(
                http_server_requests_seconds_sum{
                  namespace="devsecops",
                  job="{{args.service-name}}"
                }[5m]
              )
            )
            /
            sum(
              rate(
                http_server_requests_seconds_count{
                  namespace="devsecops",
                  job="{{args.service-name}}"
                }[5m]
              )
            )